### PR TITLE
Add docker prometheus docs

### PR DESCRIPTION
**Pull request by dylanschultzie**
Signed-off-by: Dylan Schultz <dylanschultz311@gmail.com>

### CODE REVIEW

**Comment by dylanschultzie** [comment]
@JakeHartnell hey why did you close this?

**Comment by nullmames** [comment]
i can check this in the next day or so

**Comment by the-frey** [comment]
LGTM

**Comment by the-frey** [comment]
Hey, thanks for the contribution. 

After a fair bit of discussion we've decided not to merge this, as mainnet is already out - so most folk in the validator set _should_ already have monitoring and alerting in place.

Juno has a moderate-to-large amount of docs already, and we're currently looking at pruning back some of the less relevant/viewed stuff in any case.

This might be better off as a blogpost on your blog (assuming you have one) as it's likely not something that we would need to maintain going forward.

I say that as somebody who is going to be writing a series on secure validator setups - which will be on my blog rather than in the Juno docs, because they don't really belong in the Juno docs 🙂 

We've updated our further reading section with a link to the original dockerized setup article, so folk who are curious can experiment (https://medium.com/cypher-core/cosmos-how-to-set-up-your-own-network-monitoring-dashboard-fe49c63a8271)

**Comment by dylanschultzie** [comment]
Sounds good!

**Pull request closed without merging**
