### PR TITLE
Added guide for Relayer - Rly - IBC-Go relayer

### PR DESCRIPTION
**Pull request by StakeandRelax-Validator**
We had written the missing guide just few days before it's removal... so we hope that it will be wellcome anyway!

### CODE REVIEW

**Comment by StakeandRelax-Validator** [comment]
ok, just checked and last version is 2.2.0 (not anymore 2.1.2 as in the guide) but the commands will be the same. Unfortunately the relayers fodler is missing now from your repository (I think that it has been removed because not being mantained).
I you want to restore it, I could help to update the hermes guide too.

**Comment by Reecepbcups** [comment]
Perfect thank you for taking the time to check.

I'll work to get this in. If I'm not able to edit your PR directly I'll cherry pick your commits in from here to a latest branch fix. Then you'll be able to PR into that branch the hermes patches 🙏🏻

**Comment by Reecepbcups** [comment]
@StakeandRelax-Validator I pulled this into another PR commit (with you set as author) and merged in with some minor grammatical changes. 

If you would like to add a hermes based guide as well, I am happy for you to do so.
Just make rly its own subpage, and then hermes a subpage as well :)

**Comment by manueldalb2** [comment]
I would be very happy to contribute. I will update the old Hermes guide with the new features of the latest version and maybe few more tips

**Comment by StakeandRelax-Validator** [comment]
I would be very happy to contribute. I will update the old Hermes guide with the new features of the latest version and maybe few more tips

**Pull request closed without merging**
